import { BrowserWindow } from "electron";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export const createWindow = (): BrowserWindow => {
  /* Create the browser window.
   * WebPreferences Options can be found here:
   * https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions
   */
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1280,
    resizable: false,
    webPreferences: {
      sandbox: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    icon: "../renderer/assets/logo-512.png",
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  return mainWindow;
};
